storageType: "sql" # доступны memory, sql
logger:
  level: "INFO"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "mysecretpassword"
  dbName: "postgres"
httpServer:
  bindAddress: "localhost"
  bindPort: "8080"
  timeout: "30s"
